### ISSUE TITLE
Help: Invoke to direct decode wmbus telegram

### ISSUE THREAD

**Issue by 0xfgarcia** [CBrunsch/scambus#2]
I'm trying to parse a wmbus packet, some help on how to invoke the script to directly decode this packet ¿?

44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F

Thanks.

**Comment by CBrunsch** [comment]
Just created a little script to parse frames from arguments and from files. However, your Wireless M-Bus frame features a manufacturer specific application layer which is not featured by scambus. Scambus only supports IEC standardised layers.

Btw, the frame you captured seems to be corrupt. The first byte indicates the frame length which does not match the effective length in your provided example.

```shell
wmbus@risk:~/dev/scambus$ ./reader.py -v -t '44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F'
filename:  
text:  44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F
verbosity:  2
hex:  44 D3 10 13 17 05 00 50 04 7A AF 00 30 05 2F 2F 0C 06 00 00 00 00 04 6D 03 2C 34 25 0C 13 21 33 00 00 8C 40 13 00 00 00 00 8C 80 40 13 00 00 00 00 0B 3B 13 00 00 0B 2D 00 00 00 2F 2F 2F
WARNING: frame length field does not match effective frame length! Decoding might be unreliable. Check your input.
frame[0]:  68
len(frame)-1:  61
Sep 03 13:34:18 DXP 50 00 05 17 SND-UD Records: 5
--
CI Detail:	AF (Manufacturer specific Application Layer, SND-UD)
header:		
--wmbus@risk:~/dev/scambus$ ./reader.py -v -t '44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F'
DIFs:	00 (Instantaneous value, No data)
VIFs:	30 (Power J/h)
Value:	
--
DIFs:	05 (Instantaneous value, 32 Bit Real)
VIFs:	2F (Power 10⁴ W)
Value:	00 06 0C 2F
--
DIFs:	00 (Instantaneous value, No data)
VIFs:	00 (Energy mWh)
Value:	
--
DIFs:	00 (Instantaneous value, No data)
VIFs:	04 (Energy 10¹ Wh)
Value:	
--
DIFs:	6D (Minimum value, variable length)
VIFs:	03 (Energy Wh)
Value:	00 00 00 2D 0B 00 00 13 3B 0B 00 00 00 00 13 40 80 8C 00 00 00 00 13 40 8C 00 00 33 21 13 0C 25 34
--
```

**Comment by mmuruev** [comment]
Can you share this. I'm digging the project. And found out that this DIF VID part made in horrible way. Basically utils construct it  by string XML concat so no 'decoded' structure inside the 'driver'. I'm pretty sure this is all data there that I have. But for make sure I can rerun frame.

**Comment by bencaby** [comment]
Hi guys I'm trying to decode this frame 
20 44 2D 2C 97 18 58 68 1D 16 **8D** 20 55 82 E2 F5 23 CC EE ED C2 B1 1C 50 35 0B EA CE 7E 01 D0 3A AD
all the libraries I tested until now gives me incoherent data. 
I cannot find the right spec for CI-Field = 0x8D [0x8D: 'Extended Link Layer II (8 Byte)']
I'm pretty sure byte 12 (**55**) is a sequence number as it increase by one each new message.
Then I'm lost when I try to decode this part: 
 82 E2 F5 23 CC EE ED C2 B1 1C 50 35 0B EA CE 7E 01 D0 3A AD
Are we looking for a header ? Is 82 a new CI-Field ? [0x82: 'For future use',] 

My meter is a kamstrup flow IQ 3100 and it should use 128bits AES encryption.

I hope you can help me ...
Regards.

**Comment by CBrunsch** [comment]
Maybe these papers help you move forward
- https://www.iot.com.tr/uploads/pdf/Telit_Wireless_M-bus_2013_Part4_User_Guide_r14.pdf
- https://www.diva-portal.org/smash/get/diva2:847898/FULLTEXT02

And have a look at chapter 4.2.7 ELL in this paper https://www.compass-security.com/fileadmin/Research/White_Papers/2013-01_wireless-mbus-security.pdf
